# Generated by Django 5.1.5 on 2025-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_aplicacao', '0002_sobremesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremesa',
            name='imagem',
            field=models.ImageField(default='/default/image/path.png', upload_to='sobremesas/'),
        ),
    ]
