# Generated by Django 5.1.5 on 2025-01-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_aplicacao', '0003_sobremesa_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobremesa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='sobremesas/'),
        ),
    ]
